Fix size_of() for strong_typedef_wrapper wrapped types
yandex/ozo pull request #104
Opened 2018-12-27 13:56 UTC by thed636

The problem is what the previous fix is not correct. It leads to application
of size calculation algorithm for arrays instead of default algorithm for
dynamic size data.

New test are added to address this problem.

2018-12-27 16:12 UTC, elsid requested changes

2018-12-27 16:12 UTC, elsid commented on tests/binary_serialization.cpp
> +TEST_F(send_frame, should_write_pg_bytea_as_bunary_byte_buffer) {
binary?

2018-12-27 19:28 UTC, thed636 commented on tests/binary_serialization.cpp
> +TEST_F(send_frame, should_write_pg_bytea_as_bunary_byte_buffer) {
**Done**

2018-12-29 09:55 UTC, elsid approved these changes

2018-12-29 17:17 UTC, merged