Drafto Failover framework
yandex/ozo pull request #129
Opened 2019-05-16 15:05 UTC by thed636

2019-05-22 13:50 UTC, yagzalex commented on include/ozo/detail/cancel_timer_handler.h
> +template <typename TimeConstrain, typename Handler>
Did you mean `TimeConstraint`?

2019-05-24 09:48 UTC, thed636 commented on include/ozo/detail/cancel_timer_handler.h
> +template <typename TimeConstrain, typename Handler>
Yep, thanks.

2019-06-20 08:02 UTC, yagzalex requested changes

2019-06-20 08:02 UTC, yagzalex commented on include/ozo/failover/retry.h
> +    auto times(int n) const {
Maybe you should named that as 'tries'. The name 'times' is really confusing, cause it can be misunderstood as time constraints or something.

2019-06-20 08:02 UTC, yagzalex commented on tests/failover/retry.cpp
> +    EXPECT_EQ(duration{0}, ozo::failover::detail::get_try_time_constraint(3s, 0, now));
Don't you mean to use 'deadline' from here? Otherwise, I don't see a big difference with 'should_return_zero_duration_for_try_count_zero' test.

2019-06-20 08:02 UTC, yagzalex commented on include/ozo/failover/retry.h
> +    auto operator * (int n) const { return times(n); }
Crazy thought. I think it would be handy to also have
```
template <typename ErrorConditions>
auto operator * (int n, retry_strategy<ErrorConditions> rs);
```
Because when you write `ozo::request[ozo::failover::retry(ozo::errc::network) * 3](...)` it is a little bit hard to find the exact counts of tries.
And this will make it easier `ozo::request[3 * ozo::failover::retry(ozo::errc::network)](...)`

2019-06-20 11:29 UTC, thed636 commented on include/ozo/failover/retry.h
> +    auto times(int n) const {
**Done**

2019-06-20 11:32 UTC, thed636 commented on tests/failover/retry.cpp
> +    EXPECT_EQ(duration{0}, ozo::failover::detail::get_try_time_constraint(3s, 0, now));
Yeah, thanks!

2019-06-20 12:08 UTC, thed636 commented on include/ozo/failover/retry.h
> +    auto operator * (int n) const { return times(n); }
**Done**

2019-06-21 07:40 UTC, yagzalex approved these changes

2019-06-21 08:34 UTC, merged