Remove redundant post
yandex/ozo pull request #98
Opened 2018-12-10 10:32 UTC by thed636

2018-12-10 13:12 UTC, elsid requested changes

2018-12-10 13:12 UTC, elsid commented on include/ozo/impl/async_request.h
> +        };
useless semicolon

2018-12-10 13:12 UTC, elsid commented on tests/impl/async_request.cpp
> +    // EXPECT_CALL(strand, post(_)).InSequence(s).WillOnce(InvokeArgument<0>());
just remove this line

2018-12-10 13:12 UTC, elsid commented on tests/impl/async_get_result.cpp
> +    // EXPECT_CALL(m.callback_executor, post(_)).InSequence(s).WillOnce(InvokeArgument<0>());
just remove this line

2018-12-10 15:46 UTC, thed636 commented on include/ozo/impl/async_request.h
> +        };
**Done**

2018-12-10 15:46 UTC, thed636 commented on tests/impl/async_request.cpp
> +    // EXPECT_CALL(strand, post(_)).InSequence(s).WillOnce(InvokeArgument<0>());
**Done**

2018-12-10 15:46 UTC, thed636 commented on tests/impl/async_get_result.cpp
> +    // EXPECT_CALL(m.callback_executor, post(_)).InSequence(s).WillOnce(InvokeArgument<0>());
**Done**

2018-12-11 17:05 UTC, elsid approved these changes

2018-12-12 08:34 UTC, merged